apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-docker
spec:
  params:
    - name: IMAGE
  workspaces:
    - name: source
  steps:
    - name: build
      image: gcr.io/cloud-builders/docker
      workingDir: $(workspaces.source.path)
      script: |
        docker build -t $(params.IMAGE) .
        docker push $(params.IMAGE)
